"use client"

import DrawrComp from "@/components/DrawrComp";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious  } from "@/components/ui/carousel";
import { Card, CardContent } from "@/components/ui/card";
import { CardWithForm } from "@/components/CardWData";
const dmmylist = [{
    "item": "refr_room/refrigeration station etc.mtl",
    "name": "refr_room/refrigeration station etc.obj",
    "date": "2021-05-28"
  },
  {
    "item": "frame_design/frame design.mtl",
    "name": "frame_design/frame design.obj",
    "date": "2017-07-24"
  },

]

export default function Page() {
  return (
    <div className=" text-center mx-auto bg-gradient-to-r from-emerald-700 via-neutral-600 to-blue-800">
      <div>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </div>

<main className="flex flex-col min-h-screen">
        {/* Main Central Display Section */}
        <div className="flex-grow p-8">
          <h1 className="text-3xl font-bold mb-4">Main Display</h1>
          {/* Your main content here */}

          {/* ... */}
        </div>

        {/* Listview Section */}
        <div className="p-4 bg-teal-900">
          <h2 className="text-2xl font-semibold mb-4">Listview</h2>
        <Carousel>

        <CarouselContent>
        {dmmylist.map((lst, index) => (
          <CarouselItem key={index} className="md:basis-1/2 lg:basis-1/3">
              <CardWithForm indexx ={index} lxss={lst}/>

          </CarouselItem>
        ))}
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
  </Carousel>
        </div>
      </main>
    </div>
  );
}